# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#posts'
    weight: 20
  - name: Blogs
    url: '#projects'
    weight: 30
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50
